name: Version check

on: [workflow_dispatch]

jobs:
  # Confirms all version numbers match.
  versioncheck:
    name: Version Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check three version numbers
        run: |
          MAINFILE="disable-all-wp-updates.php"
          NEWVERSION1=`grep "^Stable tag:" readme.txt | awk -F' ' '{print $NF}'`
          echo "readme.txt version: $NEWVERSION1"
          NEWVERSION2=`grep "^[ 	\*]*Version[ 	]*:[ 	]*" $MAINFILE | awk -F' ' '{print $NF}'`
          echo "$MAINFILE version: $NEWVERSION2"
          if [ "$NEWVERSION1" != "$NEWVERSION2" ]; then echo "Version in readme.txt & $MAINFILE don't match. Exiting...."; exit 1; fi
          echo "Version numbers match."


